version: "3"
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./messaging-api/src/config/migrations/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRE_DB=messaging

  api:
    image: messaging-api
    build: ./messaging-api
    # volumes:
    #   - "./messaging-api:/usr/src/app"
    #   - "./messaging-api/node_modules:/usr/src/app/node_modules"
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=docker
  
  web:
    image: webapp
    build: ./webapp
    # volumes:
    #   - "./webapp/node_modules:/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - api
